name: Deploy React App to S3

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.0+sha512.76e2379760a4328ec4415815bcd6628dee727af3779aaa4c914e3944156c4299921a89f976381ee107d41f12cfa4b66681ca9c718f0668fa0831ed4c6d8ba56c

      - name: Create Env File
        run: |
          touch .env
          echo VITE_API_URL=${{ secrets.VITE_API_URL }} >> .env
          echo VITE_COGNITO_CLIENT_ID=${{ secrets.VITE_COGNITO_CLIENT_ID }} >> .env
          echo VITE_COGNITO_AUTHORITY_URL=${{ secrets.VITE_COGNITO_AUTHORITY_URL }} >> .env
          echo VITE_COGNITO_AUTH_DOMAIN=${{ secrets.VITE_COGNITO_AUTH_DOMAIN }} >> .env

      - name: Install Dependencies
        run: pnpm install

      - name: Build React App
        run: pnpm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/brachio-dev-role-for-frontend-github-actions
          aws-region: ap-northeast-1

      - name: Sync S3 Bucket
        run: |
          aws s3 sync dist s3://${{ env.S3_BUCKET_NAME }}/ --delete
